### ISSUE TITLE
Crash Report 1178256892

### ISSUE THREAD

**Issue by Skrundead** [wowsims/sod#505]
Link:
https://wowsims.github.io/sod/rogue/#eJztU01oE0EU3je73Z28ZNvJaGEyeKi5uAYqm01XmnrINt6KSA8egp4UIrUUFAuieNEFtS0ectSI2JN3o17EQ1TQBlEs+AciBvFULxWhUgR1NpueLHiwogc/lve+/d68b96yM2hREkCNQDkloA1QgQlYAOCavEPRHJ86eKp6nOnCGzBzFwEN9q1mq9gObdTZ09NosqX9YtHEJLsX2uK96by9JdBiD9XL60h9dB3EjOUsrmSQssc127l6Wyj2PLSdN2plkjXnQHwBZ2Y1o2zvXoq2uDEXxdXPKRU/qI1M9u6A+ATKtnXFjojBPoa21+f0DOsnrTPQXwO9CTBy3sA20f7jj4LPw98e4VdYIlqZCBjLDBY813X9Qdd3PUWjJ5/38n5+3KjQQ9rkEyJ0TKM12YM6/WpnTTSQuNPckGRE47vlKA7znWhnk5hogCrS6JSyXC81uR6CJlUbgo+JeqcYnWdah8ir2SvjxHfJIrp8B7JsL6YakOCERZXZyjo+3ebZiowTL8sAfV7AVBaRNjrFm846jelcn1LImCYtVJLnT0eErgw5hG+R8ucO2Z2X+7KA2/k2lDlBdW7fB+wMaFB1YeO1hbXPi5Ru5v1y05r84ALIbj62AHXQQkK4lm3qifhn7A3SMdkcZOqXI7RKxVh5Vtp6uIOXJa+m01ehzeme6onq1IDviqHcP3aXl88GG+KD87/lw+T3jZlDId+JwbWgeOTo8rnWvhel0W4lqMAP2Z2Ndg==

RNG Seed: 2991362131

using CritMultiplier() for spellID 17347 which has no DefenseType
Stack Trace:
goroutine 123 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0x97200, 0x2391010})
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*Spell).CritMultiplier(0x2048f00, 0x23503c0)
	/home/runner/work/sod/sod/sim/core/spell_outcome.go:638 +0x11
github.com/wowsims/sod/sim/core.(*SpellResult).applyAttackTableCritSeparateRoll(0x20490d8, 0x20b8a20, 0x2048f00, 0x23503c0)
	/home/runner/work/sod/sod/sim/core/spell_outcome.go:484 +0xb
github.com/wowsims/sod/sim/core.(*Spell).OutcomeMeleeSpecialHitAndCrit(0x2048f00,...

**Comment by Skrundead** [comment]
Hemo bug idk what the issue is
