### ISSUE TITLE
Crash Report 252016449

### ISSUE THREAD

**Issue by deadryze** [wowsims/sod#68]
Link:
https://wowsims.github.io/sod/enhancement_shaman/#eJzj4uRgUmAyYJzAxOjEpMAoxCA1kZWLLSAnsTK1SIBNQlKBXauWi0Vg2xceINn3hIeLWeBtIRe7wIMGXonvjFzcAju+8EicZ9PY8F0CKPrlCY/EdjYuDoH7n3k0dgOFWAQmNzECJVYFalwGq9gOVA7UxyLQ/QVk1kZDIPPnZ5DhcyeDFM4BmvARicFgxKLBbMFsNZeZ6wUTwyigCxAyIFXHKyYGJy4ORgEmCSYHxgpGLwM0oGtgamBqZGhkYGAIE0AFASwRHEkMWUwSjAUnGGcxMkxi4pLi4GCSYFZg0WBROsXMCbHHz0EQwhBxkJw1EwRO2ltCRC7YK6aBwTV7o1nMHNeaeIU4fFLLUnMUjEwlpBU4tAZZ+vnQ6EAVcxwmUmSOgNR/6rgDCRhCqEoHy8z8D60nQ67aO0JlHCIYAbP1WvQ=

RNG Seed: 1907758783

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/sod/sod/sim/wasm/main.go:49 +0x10
panic({0xb1c60, 0xc5bc20})
	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.FillTalentsProto({0x230588, 0x283bb20}, {0x20601b0, 0x30}, {0x19, 0x1d, 0x1a})
	/home/runner/work/sod/sod/sim/core/character.go:646 +0x1d
github.com/wowsims/sod/sim/shaman.NewShaman(0x2840000, {0x20601b0, 0x30}, 0x2860000, {0x2, 0x4, 0x4})
	/home/runner/work/sod/sod/sim/shaman/shaman.go:32 +0x1c
github.com/wowsims/sod/sim/shaman/enhancement.NewEnhancementShaman(0x2840000, 0x28097a0)
	/home/runner/work/sod/sod/sim/shaman/enhancement/enhancement.go:43 +0x19
github.com/wowsims/sod/sim/shaman/enhancement.RegisterEnhancementShaman.func1(0x2840000, 0x28097a0)
	/home/runner/work/sod/sod/sim/shaman/enhancement/enhancement.go:16 ...

**Comment by deadryze** [comment]
Just read other post this was due to importer. closing ticket till function is added.
