### ISSUE TITLE
Crash Report 2079990381

### ISSUE THREAD

**Issue by MetalJacx** [wowsims/sod#905]
Link:
http://localhost:3333/sod/enhancement_shaman/#eJztVE1IVFEUnnPfm5k3x3n2vKi9uWaM0w8XYezNTGMpwUxCERKh0UJamWCYCA0JUjvxr3I11EoXNWCRVJK4K4MkiGxlSj8WQbqIQFqUQU4/WvfOjJMF4SKjFp3Ffd/7vu+e+865910s1oiXcGLBToiSfVAPTRAj4yS/nWCcQNVGE7zAYZDAMIEoTAPUwTDsbYIEgSQAtbFpREdNy5FTjScMh7nL6yy9DKgZS3GdX7rmQdWY6dDRady/rZuJCkRj7rA56eBd8wxzjHejgnTy4QVTvIz0gnnRyXuGpbJ0SzcHnHxUKJrx9KPOR1JoflTnbxal+72Y+jKXJ5OSfj6h896uIoGmhOFLZ5FY9vOYLsbFMbn4BWEecAjQ9ywFVGPygx7kmmI4OYjKiay8DmLqSXc7uM+APQ5kEGAKiCEqVit7VJwhtv/xR4Mm4G9/wmoxR2xVbvGfQI04LfUQg2rLCltW0MqGPyyZUDAg+VAgHPBLEA5lDWKm1mBrPq+aChagiznRrt2p5Q6fhuJc+gNWK3pQHwHM8BQqVkj5qDULrM3e8Kxg12fytB/kig9RCP7ysmD4uzAbyQrby3YIoQCdzI6K1rknQ4d+8N+r5faMEMj4NSbXfZEAnwuFxS/9FFmafjXNqMpIpY0WsyLMK12nqZQ02GQuVMrDW1Km5CcP3cDYz3JYyOJhdFvUzURCdGiPTosbJ5tc3AHUx7xYWJqvARVWhDBz3QWp3VwwU56rwrOJlfzSI4t63cZdq5quF3KFMmai7stBV1BSE7VcZcuA5rB0i4bk3hQxD+b63IgjsLyP2Q2lAbYNN1PfikyyranyHZRUZ8oPWa3ZlsfGIUmgH2zniOimqfjGFFf64B2I5qVBftTT3yfjQaQizTyMlBxNxZNIMK5o0x061fY3tjW2eMstM1L6j91b/Gx0TfJsHfqtPAb7ujbfISKQGmNXohXHjr/tfnDocWR3RonWwTcZIch0

RNG Seed: 2580050280

simulation failed: No random suffix with id: 1458
Stack Trace:
goroutine 358 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x98
panic({0x103cb40?, 0xc00153e060?})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/sod/sim/core.NewItem({_, _, _, _})
	/home/runner/work/sod/sod/sim/core/database.go:262 +0x2a7
github.com/wowsims/sod/sim/core.NewEquipmentSet({{0x3299, 0x5b2, 0x0, 0x655a4}, ...

**Comment by kayla-glick** [comment]
Hey @MetalJacx can you provide some details about what you were doing when this error occurred? I tried to import your link but don't receive an error. The belt is missing, however
