### ISSUE TITLE
Crash Report 158941431

### ISSUE THREAD

**Issue by mturekk** [wowsims/sod#986]
Link:
http://localhost:3333/sod/hunter/#eJztVE1IVFEUfufOj3eOvnre/HlzR2QaMl5DM7yZcSS1mJeLGKTFEC1cRQmGlqE0ELWLMshKmBaSuRqQUIIBEYLIRWIFugmNElsl1UIjSIvKfu3OzJthkHbZz6KzePd733fuPefcn4OcEoXosAsMEoXDMEDgLIklCIwSaNpGQYWRDDZgHmABIEZaYBT2tUMSyBRAkgCT+CdEe6zzyJm2k4pV3e0m3quAVJm7L2u3Uk60KjPjsvg+W5KxWPmWAvVKoza7whGVz+OyyrRLwokqz5dkLdXPBbr3WtaeflcFmhIouZZGL4U6nPF7IdCDDHfjo6xd7nEJ9PiNrH097xJBvkzIaFH6TgjY915GCYuUoX5Qr9mCIWpRiJYuFKKkHU4XXQRbAkgSLKMAtwFWASYAHgFxi1JtiwDLAA0PrbhApP/2W40twt9O4U/ZKyI1uSgoRBUXcQTEXYzBAIh31w7dkABodvn0cG04oOuhsB7SwwFfKFSr63owpAeDMWsLbZWOTVpUC5ahgxehjb7t0uweAdDiC8exEpFTtNORIRC0A4XgC/lDcaww3d91aNTkdX8wzjhXUfYUoyOYU/NurIpzLPVuplZGWiWeiREO13AxKD0dP1PrTPVDK7Ny0iCxndyLblad8bMXrKLXoGMM7Gild1POA+bInLwym0tWEq2Dp8c7ayor51vW06JBMFFsHqu8Yv1sEYquHGeVvLyQze8PK+EFu8XcvBrLGEPFu8ksSsxAImrKJdjMo7iHNRaGETRu8pQgjkHuNJB7VWpjjptgpsYz+x3w14bj+SPrnoJe89JrxiqBabPJUGPWRPXGPIFBkCahinFKFbtH2pFVliOBHIgSz4TFkf07ZJRmgd9wDl5P23SkPsvMRLYezdhcJJiw0PlzMqP72061dbrrdDXi/cc6nNZrbMg621O/tI7C1zYmD2HZA+seNuo7upYvTB98EtlrKkYL/ACZG8hM

RNG Seed: 309627834

Simulation Failure:
simulation failed: No random suffix with id: 611
Stack Trace:
goroutine 10090 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x98
panic({0x1407060?, 0xc06be60d20?})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/sod/sim/core.NewItem({_, _, _, _})
	/home/runner/work/sod/sod/sim/core/database.go:264 +0x2f9
github.com/wowsims/sod/sim/core.NewEquipmentSet({{0x36256, 0x0, 0x0, 0x656b5}, {0x5686, 0x0, 0x0, 0x0}, {0x374df, 0x0, ...}, ...})
	/home/runner/work/sod/sod/sim/core/database.go:291 +0xc6
github.com/wowsims/sod/sim/core.ProtoToEquipment(_)
	/home/runner/work/sod/sod/sim/core/database.go:298 +0xf8
github.com/wowsims/sod/sim/core.NewCharacter(_, _, _)
	/home/runner/work/sod/sod/sim/core/character.go:123 +0x4ab
github.com/wowsims/sod/sim/core.NewAgent(0xc06a52b9e0?, 0x0?, 0xc044b9e100)
	/home/runner/work/sod/sod/sim/core/agent.go:173 +0x112
github.com/wowsims/sod/sim/core.NewParty(0xc06c080000, 0x0, 0xc044b8bf40)
	/home/runner/work/sod/sod/sim/core/raid.go:34 +0x1dc
github.com/wowsims/sod/sim/core.NewRaid(0xc044b6f900)
	/home/runner/work/sod/sod/sim/core/raid.go:157 +0x1e5
github.com/wowsims/sod/sim/core.(*Environment).construct(0xc06be76000, 0xc044b6f900, 0xc044b5cf50)
	/home/runner/work/sod/sod/sim/core/environment.go:73 +0x136
github.com/wowsims/sod/sim/core.NewEnvironment(0xc000394400?, 0xbb000e?, 0x48?)
	/home/runner/work/sod/sod/sim/core/environment.go:54 +0x54
github.com/wowsims/sod/sim/core.NewSim(0xc044b9c900)
	/home/runner/work/sod/sod/sim/core/sim.go:184 +0x25
github.com/wowsims/sod/sim/core.runSim(0xc044b9c900, 0xc06b2261e0, 0x0)
	/home/runner/work/sod/sod/sim/core/sim.go:139 +0x87
github.com/wowsims/sod/sim/core.(*bulkSimRunner).getRankedResults.func2.2({0xc044b9c900?, 0xc044b800f0?, 0xc0443fd650?})
	/home/runner/work/sod/sod/sim/core/bulksim.go:315 +0x6e
created by github.com/wowsims/sod/sim/core.(*bulkSimRunner).getRankedResults.func2 in goroutine 9596
	/home/runner/work/sod/sod/sim/core/bulksim.go:310 +0x79

Press Ok to file crash report

EDIT 1: I manually pasted the complete traceback. The automatic crash report seemed to truncate the original

EDIT 2: It looks like this is caused by [Pyremail Wristguards](https://www.wowhead.com/classic/item=11765/pyremail-wristguards) [of the Monkey], which I was including as an item in the Batch simulator. When I removed this from the considered items, I no longer ran into this.

**Comment by kayla-glick** [comment]
Hey @mturekk 👋 this seems to be a common issue with the old batch sim. The one on SoD is currently considered not-properly functional so bugs related to it aren't really surprising
